### PR TITLE
Fix GetContents and SetContents.

### PR DESCRIPTION
**Pull request by howmanysmall**
These were [removed today](https://twitter.com/CloneTeee1019/status/1298707024369389573), so to keep this functionality and prevent [errors like this](https://twitter.com/Xuleos_/status/1298721822913961984), I just reimplemented the functions in pure lua.

### CODE REVIEW

**Comment by howmanysmall** [comment]
hang on need to sign the cla

**Comment by howmanysmall** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoteTheMighty** [comment]
Thanks for your contribution! Generally, Roblox's policy is not to remove any public APIs, deprecated or otherwise. I'm following up with other Roblox folks to figure out what happened here, and look into reverting the removal.

If for whatever reason I get word that deletion was intentional and should stick, then I can follow up with you on getting this patched up on the Rojo side.

**Comment by CloneTrooper1019** [comment]
The API changes appear to have been rolled back.
https://github.com/CloneTrooper1019/Roblox-Client-Tracker/commit/501e34f602017d7385c5c7814f2c6914a9f825d0

**Comment by howmanysmall** [comment]
Closed.

**Pull request closed without merging**
